.Dd December 26, 2015
.Dt STAGIT-INDEX 1
.Os
.Sh NAME
.Nm stagit-index
.Nd static git index page generator
.Sh SYNOPSIS
.Nm
.Op Ar repodir...
.Sh DESCRIPTION
.Nm
will create an index HTML page for the repositories specified and writes
the HTML data to stdout.
The repos in the index are in the same order as the arguments
.Ar repodir
specified.
.Pp
The basename of the directory is used as the repository name.
The suffix ".git" is removed from the basename, this suffix is commonly used
for "bare" repos.
.Pp
The content of the follow files specifies the meta data for each repository:
.Bl -tag -width Ds
.It .git/description or description (bare repos).
description
.It .git/owner or owner (bare repo).
owner of repository
.El
.Pp
For changing the style of the page you can use the following files:
.Bl -tag -width Ds
.It favicon.png
favicon image.
.It logo.png
32x32 logo.
.It style.css
CSS stylesheet.
.El
.Sh SEE ALSO
.Xr stagit 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
