.Dd December 20, 2015
.Dt URMOMS 1
.Os
.Sh NAME
.Nm urmoms
.Nd static git page generator
.Sh SYNOPSIS
.Nm
.Op Ar repodir
.Sh DESCRIPTION
.Nm
writes HTML pages for the repository
.Ar repodir
to the current directory. The following files will be written:
.Bl -tag -width Ds
.It atom.xml
Atom XML feed
.It files.html
List of files in the latest HEAD commit, linking to the file.
.It log.html
List of commits in order of most recent to old of the commits (top to bottom),
each commit links to a page with a diff and diffstat of the commit.
.El
.Pp
For each file in HEAD a file will be written in the format:
file/filepath.html. This file will contain the textual data of the file
prefixed by line numbers. The file will have the string "binary file"
if the data is considered to be non-textual.
.Pp
For each commit a file will be written in the format:
commit/commitid.html . This file will contain the diff and diffstat of the
commit. It will write the string "binary files differ" if the data is
considered to be non-textual.
.Pp
For changing the style of the page you can use the following files:
.Bl -tag -width Ds
.It logo.png
32x32 logo.
.It favicon.png
favicon image.
.It style.css
CSS stylesheet.
.El
.Sh SEE ALSO
.Xr urmoms-index 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
